on:
  pull_request:
   branches : [ "main" ]
  schedule:
  - cron: "20 7 * * 1-5"

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            console.log(result)
