name: README Repos List
on:
  schedule:
    - cron: "55 2 * * *"
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: Run readme-repos-list
        uses: koj-co/readme-repos-list@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          query: "Octocat in:readme"
          max: 10
