name: Gitee repos mirror periodic job

on:
  pull_request:
    branches: [ master ]
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '30 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Get repo and time
      id: info
      uses: actions/github-script@v3.1
      with:
        result-encoding: string
        script: |
          core.setOutput('time', new Date(Date.now()).toISOString().replace(/[^0-9]/g, ""));
          core.setOutput('key', `${context.repo.owner}-${context.repo.repo}`);
          return context.repo.repo;
    - name: Echo repo lists
      uses: action/github-script@v3.1
    - run: |
          echo: '${{ steps.info.outputs.result }}'
        
