name: Get all repo name

on:
  pull_request:
    branches: [ main ]
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '30 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Get repo and time
      id: info
      uses: actions/github-script@v3.1
      with:
        result-encoding: string
        script: |
          console.log(context.payload)
          core.setOutput('time', new Date(Date.now()).toISOString().replace(/[^0-9]/g, ""));
          core.setOutput('key', `${context.repo.owner}-${context.repo.repo}`);
          return context.repo.repo;
    - run: |
        echo '${{ steps.info.outputs.result }}'
        
