name: Jupyter
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup tmate session
      run: |
        python --version
        pip3 install jupyter
        jupyter notebook
        curl ifconfig.me
